-- MySQL Script generated by MySQL Workbench
-- Fri Sep 28 15:32:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SS-DBCtrlTK
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SS-DBCtrlTK` ;

-- -----------------------------------------------------
-- Schema SS-DBCtrlTK
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SS-DBCtrlTK` DEFAULT CHARACTER SET utf8 ;
USE `SS-DBCtrlTK` ;

-- -----------------------------------------------------
-- Table `SS-DBCtrlTK`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SS-DBCtrlTK`.`ticket` ;

CREATE TABLE IF NOT EXISTS `SS-DBCtrlTK`.`ticket` (
  `idticket` INT NOT NULL AUTO_INCREMENT,
  `numticket` INT UNSIGNED NOT NULL,
  `numcliente` INT UNSIGNED NOT NULL,
  `estado` VARCHAR(45) NOT NULL DEFAULT 'Pendiente',
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idticket`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
