-- MySQL Script generated by MySQL Workbench
-- Tue Nov  6 16:53:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SS-MK
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SS-MK` ;

-- -----------------------------------------------------
-- Schema SS-MK
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SS-MK` DEFAULT CHARACTER SET utf8 ;
USE `SS-MK` ;

-- -----------------------------------------------------
-- Table `SS-MK`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SS-MK`.`log` ;

CREATE TABLE IF NOT EXISTS `SS-MK`.`log` (
  `idlog` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(45) NULL,
  `ipInterna` VARCHAR(45) NULL,
  `ipPublica` VARCHAR(45) NULL,
  `time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idlog`),
  UNIQUE INDEX `idlog_UNIQUE` (`idlog` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
