-- MySQL Script generated by MySQL Workbench
-- Wed Aug 22 16:05:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SS-DBFO
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SS-DBFO` ;

-- -----------------------------------------------------
-- Schema SS-DBFO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SS-DBFO` DEFAULT CHARACTER SET utf8 ;
USE `SS-DBFO` ;

-- -----------------------------------------------------
-- Table `SS-DBFO`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SS-DBFO`.`cliente` ;

CREATE TABLE IF NOT EXISTS `SS-DBFO`.`cliente` (
  `idregistro` INT NOT NULL AUTO_INCREMENT,
  `codCliente` INT(4) NOT NULL,
  `codPon` VARCHAR(4) NOT NULL,
  `nomPon` VARCHAR(60) NOT NULL,
  `numCaja` INT(2) NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idregistro`),
  UNIQUE INDEX `idregistro_UNIQUE` (`idregistro` ASC),
  UNIQUE INDEX `codCliente_UNIQUE` (`codCliente` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
