-- MySQL Script generated by MySQL Workbench
-- Fri Aug 24 17:16:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SS-DBFO
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SS-DBFO` ;

-- -----------------------------------------------------
-- Schema SS-DBFO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SS-DBFO` DEFAULT CHARACTER SET utf8 ;
USE `SS-DBFO` ;

-- -----------------------------------------------------
-- Table `SS-DBFO`.`pon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SS-DBFO`.`pon` ;

CREATE TABLE IF NOT EXISTS `SS-DBFO`.`pon` (
  `idpon` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `codigo` VARCHAR(4) NULL,
  PRIMARY KEY (`idpon`),
  UNIQUE INDEX `idpon_UNIQUE` (`idpon` ASC),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SS-DBFO`.`nap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SS-DBFO`.`nap` ;

CREATE TABLE IF NOT EXISTS `SS-DBFO`.`nap` (
  `idnap` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `codpon` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`idnap`),
  UNIQUE INDEX `idcaja_UNIQUE` (`idnap` ASC),
  INDEX `nap.fk.pon_idx` (`codpon` ASC),
  CONSTRAINT `nap.fk.pon`
    FOREIGN KEY (`codpon`)
    REFERENCES `SS-DBFO`.`pon` (`codigo`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SS-DBFO`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SS-DBFO`.`cliente` ;

CREATE TABLE IF NOT EXISTS `SS-DBFO`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `codcliente` INT NOT NULL,
  `codnap` INT NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC),
  INDEX `cliente.fk.nap_idx` (`codnap` ASC),
  CONSTRAINT `cliente.fk.nap`
    FOREIGN KEY (`codnap`)
    REFERENCES `SS-DBFO`.`nap` (`idnap`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS wrss;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP USER IF EXISTS 'wrss'@localhost;
FLUSH PRIVILEGES;
CREATE USER 'wrss' IDENTIFIED BY 'ReadWrite@SS';

GRANT SELECT ON TABLE `SS-DBFO`.* TO 'wrss';
GRANT SELECT, INSERT, TRIGGER ON TABLE `SS-DBFO`.* TO 'wrss';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `SS-DBFO`.* TO 'wrss';
GRANT ALL ON `SS-DBFO`.* TO 'wrss';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;